config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'flash_cards/:id/answer', to: 'flash_cards#answer', as: "flash_cards_answer"
  get 'flash_cards/:id/next', to: 'flash_cards#next', as: "flash_cards_next"
  get 'flash_cards/:id/previous', to: 'flash_cards#previous', as: "flash_cards_previous"
  resources :flash_cards

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
  validates :prompt, presence: true,
                   length: { minimum: 5 }

  validates :answer, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flash_cards_controller.rb
class FlashCardsController < ApplicationController

  def index
    @flash_cards = FlashCard.all
  end

  def show
    @flash_card = FlashCard.find(params[:id])
  end

  def next
    current_id = params[:id]
    next_id = FlashCard.where("id > ?", current_id.to_i).first
    if next_id === nil
      next_id = FlashCard.first
      redirect_to controller: :flash_cards, action: :show, id: next_id
      return
    end
    redirect_to controller: :flash_cards, action: :show, id: next_id
  end

  def previous
    current_id = params[:id]
    previous_id = FlashCard.where("id < ?", current_id.to_i).last
    if previous_id === nil
      previous_id = FlashCard.last
      redirect_to controller: :flash_cards, action: :show, id: previous_id
      return
    end
    redirect_to controller: :flash_cards, action: :show, id: previous_id
  end

  def answer
    @flash_card = FlashCard.find(params[:id])
  end

  def new
    @flash_card = FlashCard.new
  end

  def create
    @flash_card = FlashCard.new(flash_card_params)
    if @flash_card.save
      redirect_to @flash_card
    else
      render 'new'
    end
  end

  def update
    @flash_card = FlashCard.find(params[:id])
    if @flash_card.update(flash_card_params)
      redirect_to @flash_card
    else
      render 'edit'
    end
  end

  def edit
    @flash_card = FlashCard.find(params[:id])
  end

  def destroy
    @flash_card = FlashCard.find(params[:id])
    @flash_card.destroy

    redirect_to flash_cards_path
  end

end

private
  def flash_card_params
    params.require(:flash_card).permit(:prompt, :answer)
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_cards_helper.rb
module FlashCardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flash_cards/_form.html.erb
<%= form_with model: @flash_card, local: true do |form| %>

  <p>
    <%= form.label :prompt %><br>
    <%= form.text_field :prompt %>
  </p>

  <p>
    <%= form.label :answer %><br>
    <%= form.text_area :answer %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/flash_cards/answer.html.erb
<p>
  <div class="card" style="height: 230 rem; width: 30rem;">
  <div class="card-body">
    <h1 class="card-title"><%= @flash_card.answer %></h1>
    <a href="<%= flash_cards_previous_path %>" input class="btn btn-outline-secondary btn-lg" type="submit" value="Next" class="card-link">Previous</a>
    <a href="<%= flash_card_path %>" input class="btn btn-primary btn-lg card-link " type="submit" value="text">Prompt</a>
    <a href="<%= flash_cards_next_path %>" input class="btn btn-outline-secondary btn-lg" type="submit" value="Next" class="card-link">Next</a>
  </div>
</div>

<%= link_to 'Back', flash_cards_path %>

app/views/flash_cards/edit.html.erb
<h1>Edit Flash Card</h1>

<%= form_with model: @flash_card, local: true do |form| %>
  <p>
    <%= form.label :prompt %><br>
    <%= form.text_field :prompt %>
  </p>
  <p>
    <%= form.label :answer %><br>
    <%= form.text_area :answer %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', flash_card_path %>

app/views/flash_cards/index.html.erb
<h1>All Flash Cards:</h1>
<%= link_to 'New Flash Card', new_flash_card_path %>

<table>
  <tr>
    <th>Prompt</th>
    <th>Answer</th>
    <th colspan="3"></th>
  </tr>

  <% @flash_cards.each do |flash_card| %>
    <tr>
      <td><%= flash_card.prompt %></td>
      <td><%= flash_card.answer %></td>
      <td><%= link_to 'Show', flash_card_path(flash_card) %></td>
      <td><%= link_to 'Edit', edit_flash_card_path(flash_card) %></td>
      <td><%= link_to 'Delete', flash_card_path(flash_card),
              method: :delete,
              data: { confirm: 'Are you sure you wish to delete this flash card?' } %></td>
    </tr>
  <% end %>
</table>

app/views/flash_cards/new.html.erb
<h1>New Flash Card</h1>

<%= render 'form' %>

<%= link_to 'Back', flash_cards_path %>

app/views/flash_cards/show.html.erb
<p>
  <div class="card" style="height: 230 rem; width: 30rem;">
  <div class="card-body">
    <h1 class="card-title"><%= @flash_card.prompt %></h1>
    <a href="<%= flash_cards_previous_path %>" input class="btn btn-outline-secondary btn-lg" type="submit" value="Next" class="card-link">Previous</a>
    <a href="<%= flash_cards_answer_path %>" input class="btn btn-primary btn-lg card-link " type="submit" value="text">Answer</a>
    <a href="<%= flash_cards_next_path %>" input class="btn btn-outline-secondary btn-lg" type="submit" value="Next" class="card-link">Next</a>
  </div>
</div>

<%= link_to 'Back', flash_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyBuddy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= welcome_index_path %>">Study Buddy Home</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="<%= @current_page === 'products' ? 'active' : '' %>" ><%= link_to "Flash Cards", flash_cards_path %></li>
        </ul>
      </div>
    <%= yield %>

    <style>
      h1 {
        color: blue;
        font-family: verdana;
        font-size: 300%;
      }
      p  {
        color: red;
        font-family: courier;
        font-size: 160%;
      }
      body {background-color: powderblue;}

    </style>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>I am your Study Buddy!</h1>
<p>Let's create some flash cards online to save some paper. Study easy, study green.</p>

<style>
  h1 {
    color: blue;
    font-family: verdana;
    font-size: 300%;
  }
  p  {
    color: red;
    font-family: courier;
    font-size: 160%;
  }
  body {background-color: powderblue;}
  
</style>

<%= link_to 'My Flash Cards', controller: 'flash_cards' %>